apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: sujitht007/microservice-app:latest
        imagePullPolicy: IfNotPresent   # ✅ FIX
        ports:
        - containerPort: 3000